spring.application.name=e16095-assignment

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/help-desk
spring.datasource.username=postgres
spring.datasource.password=master_p@ssword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernatet.dialect=org.hibernate.dialect.PostgreSQLDialect