package com.unipi.e16095_assignment.mappers;

import com.unipi.e16095_assignment.dtos.LoginResponseDto;
import com.unipi.e16095_assignment.dtos.UserDto;
import com.unipi.e16095_assignment.entities.Users;
import com.unipi.e16095_assignment.enums.RoleEnum;

public class UserMapper {

    public static LoginResponseDto userEntityToResponseDtoMapper(Users user) {
        LoginResponseDto loginResponseDto = new LoginResponseDto();

        loginResponseDto.setId(user.getId());
        loginResponseDto.setUsername(user.getUsername());
        loginResponseDto.setEmail(user.getEmail());
        loginResponseDto.setRoleEnum(user.getRole());
        loginResponseDto.setAllowed(true);

        return loginResponseDto;
    }

    public static Users responseDtoToUserEntityMapper(UserDto userDto) {
        Users userEntity = new Users();

//        ID of userEntity will be auto-generated by the save operation of the repository
        userEntity.setUsername(userDto.getUsername());
        userEntity.setPassword(userDto.getPassword());
        userEntity.setEmail(userDto.getEmail());
        userEntity.setRole(RoleEnum.valueOf(userDto.getRole()));

        return userEntity;
    }

}
