package com.unipi.e16095_assignment.mappers;

import com.unipi.e16095_assignment.dtos.UserDto;
import com.unipi.e16095_assignment.entities.Users;
import com.unipi.e16095_assignment.enums.RoleEnum;

public class UserMapper {

    public static UserDto entityToDtoUserMapper(Users userEntity) {
        UserDto userDto = new UserDto();

        userDto.setId(userEntity.getId());
        userDto.setUsername(userEntity.getUsername());
        userDto.setPassword(userEntity.getPassword());
        userDto.setEmail(userEntity.getEmail());
        userDto.setRole(userEntity.getRole().toString());

        return userDto;
    }

    public static Users dtoToEntityUserMapper(UserDto userDto) {
        Users userEntity = new Users();

//        ID of userEntity will be auto-generated by the save operation of the repository
        userEntity.setUsername(userDto.getUsername());
        userEntity.setPassword(userDto.getPassword());
        userEntity.setEmail(userDto.getEmail());
        userEntity.setRole(RoleEnum.valueOf(userDto.getRole()));

        return userEntity;
    }

}
